# command output in file
logfile = "output.txt"
# print only missing clients
print_all = true
# directory for alarm files
alarm_dir = ""
# directory for output file
output_dir = ""


# Add new client_group for more clients to bing
[[client_group]]
address = "ATGRZSI511500"
interval = 5
alarmfile = "ATGRZSI511500.alarm"

#[[client_group]]
#address = "ATGRZWV601314.avl01.avlcorp.lan"
#interval = 3
#alarmfile = ""

[[client_group]]
address = "10.0.0.138"
interval = 5
alarmfile = "modem.alarm"